### ISSUE TITLE
select Hamiltonian graphs

### ISSUE THREAD

**Issue by lichengzhang1** [JarneRenders/K2-Hamiltonian-Graphs#1]
Hello,

I know the './hamiltonicityChecker' command can select non-Hamiltonian graphs, but if I want to select Hamiltonian graphs, what command should I execute?

Best wishes,
Licheng

**Comment by JarneRenders** [comment]
Use option -c to output the complement of the set of all non-hamiltonian input graphs, i.e. to output the set of all hamiltonian input graphs.

Kind regards,
Jarne
